//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library_dbEntities : DbContext
    {
        public library_dbEntities()
            : base("name=library_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_student_info> tbl_student_info { get; set; }
        public DbSet<tbl_rfid_tag> tbl_rfid_tag { get; set; }
        public DbSet<tbl_sec> tbl_sec { get; set; }
        public DbSet<tbl_yr> tbl_yr { get; set; }
        public DbSet<view_students_information> view_students_information { get; set; }
        public DbSet<tbl_book_category> tbl_book_category { get; set; }
        public DbSet<tbl_book_info> tbl_book_info { get; set; }
        public DbSet<view_book_information> view_book_information { get; set; }
        public DbSet<tbl_borrowed_book> tbl_borrowed_book { get; set; }
        public DbSet<view_book_borrow_info> view_book_borrow_info { get; set; }
        public DbSet<tbl_returned_book> tbl_returned_book { get; set; }
        public DbSet<view_book_returned> view_book_returned { get; set; }
        public DbSet<view_bookstat> view_bookstat { get; set; }
    }
}
