//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rfid_tag
    {
        public int rfid_id { get; set; }
        public string rfid_tag_id { get; set; }
        public Nullable<int> rfid_tag_active { get; set; }
        public string rfid_tag_assigned { get; set; }
    }
}
