//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_student_info
    {
        public int stud_id { get; set; }
        public string stud_id_number { get; set; }
        public string stud_fn { get; set; }
        public string stud_mn { get; set; }
        public string stud_ln { get; set; }
        public string stud_parent_number { get; set; }
        public Nullable<int> stud_active { get; set; }
        public Nullable<int> yr_id { get; set; }
        public Nullable<int> sec_id { get; set; }
        public string rfid_id { get; set; }
        public byte[] img { get; set; }
    }
}
