//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int u_id { get; set; }
        public string un { get; set; }
        public string pw { get; set; }
        public string fn { get; set; }
        public int role { get; set; }
        public int isactive { get; set; }
    }
}
