//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_book_info
    {
        public int b_id { get; set; }
        public string b_title { get; set; }
        public string b_add_info { get; set; }
        public string b_author { get; set; }
        public string b_publisher { get; set; }
        public int b_qty { get; set; }
        public int b_copyright { get; set; }
        public string b_call_no { get; set; }
        public string b_acc_no { get; set; }
        public string b_isbn { get; set; }
        public int bc_id { get; set; }
    }
}
