//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_bookstat
    {
        public long count_tbl_borrowed_book_b_id_ { get; set; }
        public int bb_id { get; set; }
        public System.DateTime bb_borrowed_date { get; set; }
        public System.DateTime bb_due_date { get; set; }
        public int bb_status { get; set; }
        public int b_id { get; set; }
        public string b_title { get; set; }
        public string b_author { get; set; }
        public string b_publisher { get; set; }
        public int b_copyright { get; set; }
        public int bc_id { get; set; }
        public string bc_detail { get; set; }
    }
}
