//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_book_borrow_info
    {
        public int bb_id { get; set; }
        public System.DateTime bb_borrowed_date { get; set; }
        public System.DateTime bb_due_date { get; set; }
        public int bb_status { get; set; }
        public string stud_id_number { get; set; }
        public string stud_fn { get; set; }
        public string stud_ln { get; set; }
        public Nullable<int> yr_details { get; set; }
        public string sec_details { get; set; }
        public int b_id { get; set; }
        public string b_title { get; set; }
        public string b_author { get; set; }
        public int sec_id { get; set; }
        public string b_ref_num { get; set; }
    }
}
